# Created using wingetcreate 1.1.2.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.2.0.schema.json
# Follow:
#   https://docs.microsoft.com/en-us/windows/package-manager/package/manifest?tabs=minschema%2Cversion-example#tips-and-best-practices
#   https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.2.0#best-practices
# Reference: https://github.com/microsoft/winget-pkgs/blob/master/doc/manifest/schema/1.2.0/installer.md
PackageIdentifier: Diskuv.OCaml
PackageVersion: 1.0.0.0
UpgradeBehavior: install
Commands:
  # PATH entry: <DiskuvOCamlHome>/bin
  # BUT ... Opam will be releasing an MSI soon so _do not conflict_
  # - opam
  # - opam-installer
  # - opam-putenv

  # PATH entry: <DiskuvOCamlHome>/usr/bin
  # BUT ... max 16 entries in Commands:[] so took only the most commonly used
  - dune
  - ocaml
  - ocamlc
  - ocamldebug
  - ocamldoc
  - ocamlfind
  - ocamlformat
  - ocamllsp
  - ocamlopt
  - ocamlrun
  - ocp-indent
  - utop
  - with-dkml
Platform:
  - "Windows.Desktop"
# Minimum OS comes from https://github.com/diskuv/dkml-runtime-distribution/blob/ff7e6bcbf3dbdb37e64b20a57e2dea0fa9d27ed5/src/windows/Machine/Machine.psm1#L14:
# > $Windows10SdkVer = "18362"
MinimumOSVersion: 10.0.18362.0
InstallerType: exe
InstallModes:
  - silent
  - interactive
Installers:
  - Architecture: x64

    # TODO: InstallerUrl/InstallerSha256/ReleaseDate needs to be updated by contributors/sign.sh!
    InstallerUrl: https://github.com/diskuv/dkml-installer-ocaml/releases/download/v1.0.0/setup-diskuv-ocaml-windows_x86_64-1.0.0.exe
    InstallerType: exe
    InstallerSha256: 32f010577a791d5595760cbb5136bd60049ffd37c8d44e68e7a8729319670a48
    ReleaseDate: 2022-08-08

    DisplayInstallWarnings: true

    InstallerSwitches:
      Silent: --ci --quiet --color=never
      SilentWithProgress: --ci
      Interactive: --color=always
      InstallLocation: --prefix "<INSTALLPATH>"

    AppsAndFeaturesEntries:
      # Keep in sync with installer\src\private_common.ml which is used by
      # https://github.com/diskuv/dkml-install-api/blob/main/package/console/common/Windows_registry.ml
      - Publisher: Diskuv, Inc.
        DisplayName: Diskuv OCaml
        # TODO: "dev" is a mistake that has been corrected in Diskuv OCaml 1.0.1+
        DisplayVersion: dev
ManifestType: installer
ManifestVersion: 1.2.0
