# Created using wingetcreate 1.1.2.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.2.0.schema.json
PackageIdentifier: Diskuv.opam
PackageVersion: 2.2.0-beta2 # BUMP
# Scope: user
UpgradeBehavior: install
Commands:
  - opam
  - opam-installer
  - opam-putenv
Platform:
  - "Windows.Desktop"
# Minimum OS comes from https://github.com/diskuv/dkml-runtime-distribution/blob/ff7e6bcbf3dbdb37e64b20a57e2dea0fa9d27ed5/src/windows/Machine/Machine.psm1#L14:
# > $Windows10SdkVer = "18362"
MinimumOSVersion: 10.0.18362.0
InstallerType: exe
InstallModes:
  - silent
  - interactive
InstallerSwitches:
  Silent: --ci --quiet --color=never
  SilentWithProgress: --ci
  Interactive: --color=always
  InstallLocation: --prefix "<INSTALLPATH>"
ReleaseDate: 2024-04-09 # BUMP

Installers:
  - Architecture: x86
    InstallerUrl: https://github.com/diskuv/dkml-installer-opam/releases/download/2.2.0-beta2-20240409/unsigned-opam-windows_x86-i-2.2.0-beta2-20240409.exe # BUMP
    InstallerType: exe
    InstallerSha256: c91f85eaff17af4deb63121176194e4d10aed4201c687144ca8f6087f2a303ce # BUMP
  - Architecture: x64
    InstallerUrl: https://github.com/diskuv/dkml-installer-opam/releases/download/2.2.0-beta2-20240409/unsigned-opam-windows_x86_64-i-2.2.0-beta2-20240409.exe # BUMP
    InstallerType: exe
    InstallerSha256: dd9c3cc89193fc81e1041af58f1e0b4000d0f5eb206f24430dfcd08aab386988 # BUMP
ManifestType: "installer"
ManifestVersion: "1.1.0"
